@startuml MVC

allowmixing

namespace model #FF8888 {
    database RemoteDatabase
    class LocalDatabase
    remoteDatabase <|--|> localDatabase
}

namespace controller #88FF88{
    class Trawler {
        Local extension is the controller for the MVC model
        ~invokeWhitelistCheck()
        ~invokeBlacklistCheck()
        ~invokeSimilarCheck()
        ~invokeWhoIsCheck()
    }
}

namespace view #8888FF {
    class toolbarInterface
    class extensionWebpage
}



BaseClass <|-- example

@enduml