@startuml projectFlow
    (*) --> "User Navigates to domain"
    -> [URL Load] "Parse domain from current URL"
    --> ===B1===
    -> "Check remote blacklist"
    -> "Remote whitelist"
    -> "URL similarity Check"
    --> ===B2===
    ===B1=== --> "WhoIs Domain Lookup"
    "WhoIs Domain Lookup" --> ===B2===
    if "Safe or Recognized Domain" then
        --> [Continue to domain] (*)
        else
        --> [Phising/potential phising - ALERT USER] (*)
    endif
@enduml