@startuml projectFlow
    (*) --> "User Navigates to domain"
    -> [URL Load] "Parse domain from current URL"
    if "Local whitelist check" then
        -> [pass] (*)
    else
        --> [fail] ===B1===
        -> "Check remote blacklist"
        -> "Check remote whitelist"
        -> "URL similarity Check"
        --> ===B2===
        --> "WhoIs Domain Lookup"
        --> ===B2===
        if "Safe or Recognized Domain" then
            --> [Continue to domain] (*)
        else
            --> [Phising/potential phising - ALERT USER] (*)
        endif
    endif
@enduml